#!/usr/bin/env python3
"""
Email Signature Generator
Generates HTML, PDF, or JPG signatures from HTML templates and employee Excel data.
All dependencies are bundled into the executable via PyInstaller.
"""

import os
import sys
import re
import shutil
import tempfile
from pathlib import Path
from typing import Optional


# ─── Path compatibility for PyInstaller executables ───────────────────────────
def get_base_dir() -> Path:
    """Returns the program base directory (works with PyInstaller and plain scripts)."""
    if getattr(sys, 'frozen', False):
        return Path(sys.executable).parent
    return Path(__file__).parent


BASE_DIR     = get_base_dir()
TEMPLATES_DIR = BASE_DIR / "templates"
OUTPUT_DIR   = BASE_DIR / "output"
DATA_DIR     = BASE_DIR / "data"

for d in [TEMPLATES_DIR, OUTPUT_DIR, DATA_DIR]:
    d.mkdir(parents=True, exist_ok=True)


# ─── Dependency imports ────────────────────────────────────────────────────────
def import_deps() -> dict:
    missing = []
    mods = {}

    try:
        import openpyxl
        mods['openpyxl'] = openpyxl
    except ImportError:
        missing.append('openpyxl')

    try:
        from PIL import Image
        import PIL
        mods['PIL'] = PIL
        mods['Image'] = Image
    except ImportError:
        missing.append('Pillow')

    if missing:
        print(f"\n[ERROR] Missing dependencies: {', '.join(missing)}")
        print("Run: pip install openpyxl Pillow")
        print("Or use the executable generated by PyInstaller.")
        sys.exit(1)

    return mods


# ─── ANSI colors ──────────────────────────────────────────────────────────────
class Color:
    RESET   = '\033[0m'
    BOLD    = '\033[1m'
    GREEN   = '\033[92m'
    BLUE    = '\033[94m'
    CYAN    = '\033[96m'
    YELLOW  = '\033[93m'
    RED     = '\033[91m'
    GRAY    = '\033[90m'

    @staticmethod
    def supported() -> bool:
        if sys.platform == 'win32':
            try:
                import ctypes
                kernel32 = ctypes.windll.kernel32
                kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
                return True
            except Exception:
                return False
        return True


USE_COLOR = Color.supported()


def c(text: str, color: str) -> str:
    return f"{color}{text}{Color.RESET}" if USE_COLOR else text


# ─── UI helpers ───────────────────────────────────────────────────────────────
def clear_screen():
    os.system('cls' if sys.platform == 'win32' else 'clear')


def header():
    clear_screen()
    print(c("╔══════════════════════════════════════════════════╗", Color.BLUE))
    print(c("║          GERADOR DE ASSINATURA DE EMAIL          ║", Color.BLUE))
    print(c("╚══════════════════════════════════════════════════╝", Color.BLUE))
    print()


def divider():
    print(c("─" * 52, Color.GRAY))


def ok(msg: str):
    print(c(f"  ✔  {msg}", Color.GREEN))


def fail(msg: str):
    print(c(f"  ✖  {msg}", Color.RED))


def info(msg: str):
    print(c(f"  ℹ  {msg}", Color.CYAN))


def warn(msg: str):
    print(c(f"  ⚠  {msg}", Color.YELLOW))


def menu(title: str, options: list[tuple[str, str]]) -> str:
    """Displays a menu and returns the user's choice key."""
    print(c(f"\n  {title}", Color.BOLD))
    divider()
    for key, desc in options:
        print(f"  {c(f'[{key}]', Color.YELLOW)} {desc}")
    divider()
    valid = [o[0].lower() for o in options]
    while True:
        choice = input(c("  Your choice: ", Color.CYAN)).strip().lower()
        if choice in valid:
            return choice
        fail("Invalid option. Please try again.")


# ─── Excel reading ────────────────────────────────────────────────────────────
def read_employees(excel_path: Path, deps: dict) -> list[dict]:
    """Reads the Excel file and returns a list of employee dicts."""
    openpyxl = deps['openpyxl']
    try:
        wb = openpyxl.load_workbook(excel_path, data_only=True)
        ws = wb.active
        employees = []
        headers = None
        for i, row in enumerate(ws.iter_rows(values_only=True)):
            if i == 0:
                headers = [str(h).strip().lower() if h else '' for h in row]
                continue
            if not any(row):
                continue
            emp = {}
            for j, val in enumerate(row):
                if j < len(headers):
                    emp[headers[j]] = str(val).strip() if val is not None else ''
            employees.append(emp)

        os.system('cls' if sys.platform == 'win32' else 'clear')
        
        return employees
    except Exception as e:
        fail(f"Não foi possível ler o arquivo Excel: {e}")
        return []


def detect_columns(employees: list[dict]) -> dict:
    """Auto-maps common column names."""
    if not employees:
        return {}
    mapping = {}
    for k in employees[0].keys():
        kl = k.lower()
        if any(x in kl for x in ['nome', 'name']):
            mapping['name'] = k
        elif any(x in kl for x in ['cargo', 'position', 'title', 'role', 'função', 'funcao']):
            mapping['position'] = k
        elif any(x in kl for x in ['tel', 'phone', 'fone', 'celular', 'whatsapp']):
            mapping['phone'] = k
        elif any(x in kl for x in ['email', 'e-mail', 'mail']):
            mapping['email'] = k
        elif any(x in kl for x in ['depart', 'setor', 'área', 'area', 'department', 'dept']):
            mapping['department'] = k
    return mapping


# ─── Templates ────────────────────────────────────────────────────────────────
def list_templates() -> list[Path]:
    return sorted(TEMPLATES_DIR.glob("*.html"))


def load_template(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def render_template(template: str, data: dict, col_map: dict) -> str:
    """Replaces {{variable}} placeholders in the template with employee data."""
    result = template

    # Map template variable names → actual Excel column keys
    var_to_col = {
        'name':       col_map.get('name', 'name'),
        'position':   col_map.get('position', 'position'),
        'phone':      col_map.get('phone', 'phone'),
        'email':      col_map.get('email', 'email'),
        'department': col_map.get('department', 'department'),
        # Portuguese aliases for backwards compatibility
        'nome':        col_map.get('name', col_map.get('nome', 'nome')),
        'cargo':       col_map.get('position', col_map.get('cargo', 'cargo')),
        'telefone':    col_map.get('phone', col_map.get('telefone', 'telefone')),
        'departamento':col_map.get('department', col_map.get('departamento', 'departamento')),
    }

    for var, col in var_to_col.items():
        value = data.get(col, data.get(var, ''))
        result = result.replace('{{' + var + '}}', value)
        result = result.replace('{{ ' + var + ' }}', value)

    # Replace any remaining column name directly
    for col, value in data.items():
        result = result.replace('{{' + col + '}}', value)

    return result


# ─── Output generation ────────────────────────────────────────────────────────
def html_to_jpg(html_content: str, output_path: Path, deps: dict):
    try:
        from html2image import Html2Image
        with tempfile.TemporaryDirectory() as tmp:
            hti = Html2Image(output_path=tmp, size=(600, 200))
            hti.screenshot(html_str=html_content, save_as="sig_tmp.png")
            img_path = Path(tmp) / "sig_tmp.png"
            if img_path.exists():
                img = deps['Image'].open(img_path)
                bbox = img.convert("RGB").getbbox()
                if bbox:
                    img = img.crop((bbox[0], bbox[1],
                                    min(bbox[2]+20, img.width),
                                    min(bbox[3]+20, img.height)))
                img.save(str(output_path), "JPEG", quality=95)
                return
    except ImportError:
        pass
    _jpg_fallback(html_content, output_path, deps)


def _jpg_fallback(html_content: str, output_path: Path, deps: dict):
    from PIL import Image, ImageDraw, ImageFont

    text = re.sub(r'<style[^>]*>.*?</style>', '', html_content, flags=re.DOTALL)
    text = re.sub(r'<[^>]+>', '\n', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    lines = [l.strip() for l in text.split('\n') if l.strip()]

    width, height = 600, max(150, len(lines) * 28 + 40)
    img = Image.new('RGB', (width, height), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)

    try:
        font      = ImageFont.truetype("arial.ttf", 16)
        font_bold = ImageFont.truetype("arialbd.ttf", 18)
    except Exception:
        font = font_bold = ImageFont.load_default()

    y = 20
    for i, line in enumerate(lines[:15]):
        f = font_bold if i == 0 else font
        draw.text((20, y), line, fill=(30, 30, 30), font=f)
        y += 26

    img.save(str(output_path), "JPEG", quality=95)


def html_to_pdf(html_content: str, output_path: Path):
    try:
        import weasyprint
        weasyprint.HTML(string=html_content).write_pdf(str(output_path))
        return
    except ImportError:
        pass
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph
        from reportlab.lib.styles import getSampleStyleSheet
        text = re.sub(r'<[^>]+>', ' ', html_content)
        text = re.sub(r'\s+', ' ', text).strip()
        doc = SimpleDocTemplate(str(output_path), pagesize=A4)
        doc.build([Paragraph(text, getSampleStyleSheet()['Normal'])])
        return
    except ImportError:
        pass
    output_path.write_text(html_content, encoding='utf-8')
    warn(f"PDF saved as HTML (install weasyprint or reportlab for real PDF): {output_path.name}")


def save_signature(html: str, filename: str, fmt: str, deps: dict) -> Path:
    base = OUTPUT_DIR / filename
    if fmt == 'html':
        path = base.with_suffix('.html')
        path.write_text(html, encoding='utf-8')
    elif fmt == 'pdf':
        path = base.with_suffix('.pdf')
        html_to_pdf(html, path)
    elif fmt == 'jpg':
        path = base.with_suffix('.jpg')
        html_to_jpg(html, path, deps)
    else:
        path = base.with_suffix('.html')
        path.write_text(html, encoding='utf-8')
    return path


# ─── Selection helpers ────────────────────────────────────────────────────────
def select_excel_file() -> Optional[Path]:
    """
    Always lists ALL .xlsx/.xls files inside the data/ folder.
    If none exist, prompts for a full path.
    """
    excels = sorted(
        list(DATA_DIR.glob("*.xlsx")) + list(DATA_DIR.glob("*.xls"))
    )

    if not excels:
        fail(f"Nenhum arquivo Excel encontrado em: {DATA_DIR}")
        info("Coloque seus arquivos .xlsx na pasta 'data', ou digite o caminho completo abaixo.")
        raw = input(c("  Caminho completo do arquivo Excel: ", Color.CYAN)).strip().strip('"')
        p = Path(raw)
        if p.exists():
            return p
        fail("Arquivo não encontrado ou inacessível.")
        return None

    print(c(f"\n  Arquivos excel na pasta data/ ({len(excels)} encontrados):", Color.BOLD))
    divider()
    for i, p in enumerate(excels):
        print(f"  {c(str(i + 1), Color.YELLOW)}. {p.name}")
    divider()

    while True:
        try:
            idx = int(input(c("  Selecione o número do arquivo: ", Color.CYAN))) - 1
            if 0 <= idx < len(excels):
                os.system('cls' if sys.platform == 'win32' else 'clear')
                return excels[idx]
        except ValueError:
            pass
        fail("Número inválido. Tente novamente.")


def select_template() -> Optional[Path]:
    templates = list_templates()
    if not templates:
        fail(f"Nenhum template .html encontrado em: {TEMPLATES_DIR}")
        info("Crie um arquivo .html na pasta 'templates' usando as variáveis {{name}}, {{position}}, {{phone}}.")
        return None

    if len(templates) == 1:
        info(f"Template encontrado: {c(templates[0].name, Color.GREEN)}")
        return templates[0]

    print(c("\n  Templates disponíveis:", Color.BOLD))
    divider()
    for i, t in enumerate(templates):
        print(f"  {c(str(i + 1), Color.YELLOW)}. {t.stem}")
    divider()

    while True:
        try:
            idx = int(input(c("  Selecione o número do template: ", Color.CYAN))) - 1
            if 0 <= idx < len(templates):
                os.system('cls' if sys.platform == 'win32' else 'clear')
                return templates[idx]
        except ValueError:
            pass
        fail("Número inválido. Tente novamente.")


def select_employees(employees: list[dict], col_map: dict) -> list[dict]:
    total = len(employees)
    name_col = col_map.get('name', list(employees[0].keys())[0] if employees else 'name')

    print(c(f"\n  Total employees loaded: {total}", Color.BOLD))

    choice = menu("Which employees?", [
        ('1', 'All employees'),
        ('2', 'Range  (e.g. employees 3 to 10)'),
        ('3', 'Single employee'),
    ])

    if choice == '1':
        return employees

    elif choice == '2':
        print()
        for i, emp in enumerate(employees):
            name = emp.get(name_col, f'Employee {i + 1}')
            print(f"  {c(str(i + 1), Color.YELLOW)}. {name}")
        divider()
        while True:
            try:
                start = int(input(c("  From (number): ", Color.CYAN)))
                end   = int(input(c("  To   (number): ", Color.CYAN)))
                if 1 <= start <= end <= total:
                    return employees[start - 1:end]
                fail(f"Invalid range. Enter values between 1 and {total}.")
            except ValueError:
                fail("Numbers only please.")

    elif choice == '3':
        print()
        for i, emp in enumerate(employees):
            name = emp.get(name_col, f'Employee {i + 1}')
            print(f"  {c(str(i + 1), Color.YELLOW)}. {name}")
        divider()
        while True:
            try:
                idx = int(input(c("  Employee number: ", Color.CYAN)))
                if 1 <= idx <= total:
                    return [employees[idx - 1]]
                fail(f"Invalid number. Enter between 1 and {total}.")
            except ValueError:
                fail("Numbers only please.")

    return employees


def select_format() -> str:
    choice = menu("Output format:", [
        ('1', 'HTML  (.html)'),
        ('2', 'PDF   (.pdf)'),
        ('3', 'JPEG  (.jpg)'),
    ])
    return {'1': 'html', '2': 'pdf', '3': 'jpg'}[choice]


def safe_filename(text: str) -> str:
    text = text.lower()
    for src, dst in [('á','a'),('à','a'),('ã','a'),('â','a'),('ä','a'),
                     ('é','e'),('è','e'),('ê','e'),('ë','e'),
                     ('í','i'),('ì','i'),('î','i'),('ï','i'),
                     ('ó','o'),('ò','o'),('õ','o'),('ô','o'),('ö','o'),
                     ('ú','u'),('ù','u'),('û','u'),('ü','u'),('ç','c')]:
        text = text.replace(src, dst)
    text = re.sub(r'[^a-z0-9_]', '_', text)
    text = re.sub(r'_+', '_', text).strip('_')
    return text

def press_to_exit() -> str:
    return input("\nPressione Enter para sair...")


# ─── Main flow ────────────────────────────────────────────────────────────────
def main():
    deps = import_deps()
    header()

    info(f"Templates : {TEMPLATES_DIR}")
    info(f"Dados     : {DATA_DIR}")
    info(f"Saída     : {OUTPUT_DIR}")
    print(c("\n\n  Certifique-se de colocar os arquivos nas pastas corretas!\n\n", Color.YELLOW))
    input("Pressione Enter para continuar...")

    os.system('cls' if sys.platform == 'win32' else 'clear')

    # 1. Select template
    template_path = select_template()
    if not template_path:
        press_to_exit()
        return

    # 2. Select Excel file (always shows list)
    excel_path = select_excel_file()
    if not excel_path:
        press_to_exit()
        return

    # 3. Load employees
    employees = read_employees(excel_path, deps)
    if not employees:
        fail("Nenhum funcionário encontrado no arquivo Excel.")
        press_to_exit()
        return

    col_map = detect_columns(employees)
    ok(f"{len(employees)} funcionário(s) carregado(s) de '{excel_path.name}'.")
    if col_map:
        info("Colunas detectadas: " + ", ".join(f"{k} → {v}" for k, v in col_map.items()))

    # 4. Select which employees
    selected = select_employees(employees, col_map)
    info(f"{len(selected)} funcionário(s) selecionados.")

    # 5. Select output format
    fmt = select_format()

    # 6. Generate signatures
    template_html = load_template(template_path)
    template_name = template_path.stem

    print()
    divider()
    print(c(f"  Gerando {len(selected)} assinatura(s) como {fmt.upper()}...", Color.BOLD))
    divider()

    name_col = col_map.get('name', list(employees[0].keys())[0] if employees else 'name')
    generated = []
    errors = []

    for i, emp in enumerate(selected):
        emp_name = emp.get(name_col, f'employee_{i + 1}')
        filename = f"{safe_filename(emp_name)}_{template_name}"

        try:
            html = render_template(template_html, emp, col_map)
            path = save_signature(html, filename, fmt, deps)
            generated.append(path)
            ok(f"[{i + 1}/{len(selected)}] {emp_name}  →  {path.name}")
        except Exception as e:
            errors.append((emp_name, str(e)))
            fail(f"[{i + 1}/{len(selected)}] {emp_name}  →  {e}")

    # 7. Summary
    print()
    divider()
    print(c(f"  Feito! {len(generated)} assinatura(s) gerada(s).", Color.GREEN + Color.BOLD))
    if errors:
        warn(f"{len(errors)} erro(s) ocorrido(s).")
    info(f"Arquivos salvos em: {OUTPUT_DIR}")
    divider()

    again = input(c("\n  Gerar mais assinaturas? (y/n): ", Color.CYAN)).strip().lower()
    if again == 'y':
        main()
    else:
        print(c("\n  Adeus!\n", Color.BLUE))


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print(c("\n\n  Operation cancelled by user.\n", Color.YELLOW))
        sys.exit(0)
